apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: ${APP_GIT_REPO}
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: docker-image
spec:
  type: image
  params:
  - name: url
    value: docker.io/${DOCKER_USERNAME}/${APP_NAME}
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: simple-pipeline-run
spec:
  pipelineRef:
    name: simple-pipeline
  trigger:
    type: manual
  serviceAccount: ${DASHBOARD_SERVICE_ACCOUNT}
  resources:
  - name: git-source
    resourceRef:
      name: git-source
  - name: docker-image
    resourceRef:
      name: docker-image
