apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: only-github-push-event
spec:
  params:
  - name: event-headers
    type: string
    description: "The GitHub event headers"
  check:
    name: deployment-condition
    image: stedolan/jq
    command:
    - bash
    args:
    - -ce
    - |
      [[ $(jq '."Ce-Github-Event"[0]' <<< '$(params.event-headers)') = *"push"* ]]
