# This pipeline will check out then build an image's code, push it to a Docker registry, 
# then deploy the application assuming a helm chart under the "chart" folder at the repository.

apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: simple-helm-pipeline-insecure
spec:
  resources: 
  - name: git-source
    type: git
  - name: docker-image
    type: image
  params:
  - name: chart-dir
    description: The relative path of the chart directory
    default: chart
  - name: replace-repo
    description: The placeholder image to be replaced
    default: replacemerepo
  - name: replace-tag
    description: The placeholder tag to be replaced
    default: replacemetag
  - name: release-name
    description: The helm release name
    default: release-name
  - name: repository-name
    description: The repository name
    default: myreponame
  - name: image-tag
    description: The image tag
    default: image-tag
  - name: image-name
    description: The image name
    default: image-name
  - name: target-namespace
    description: The target namespace
    default: tekton-pipelines
  tasks:
  - name: build-simple
    taskRef:
      name: build-credential-push
    resources:
      inputs:
      - name: git-source
        resource: git-source
      outputs:
      - name: builtImage
        resource: docker-image
  - name: deploy-simple
    runAfter: [build-simple]
    taskRef: 
      name: deploy-simple-helm-task-insecure
    resources: 
      inputs:
      - name: git-source
        resource: git-source
    params:
    - name: chart-dir
      value: $(params.chart-dir)
    - name: replace-tag
      value: $(params.replace-tag)
    - name: replace-repo
      value: $(params.replace-repo)
    - name: release-name
      value: $(params.release-name)
    - name: repository-name
      value: $(params.repository-name)
    - name: image-tag
      value: $(params.image-tag)
    - name: image-name
      value: $(params.image-name)
    - name: target-namespace
      value: $(params.target-namespace)
